### ISSUE TITLE
Clicking on Update notification does not launch APKGrabber

### ISSUE THREAD

**Issue by tjsuominen** [hemker/apkgrabber#37] opened 2019-04-12 06:25 UTC
**Description of the problem:**
After APKGrabber notifies that there are new updates available, clicking on the notification does not launch APKGrabber (to view the available updates). It just "dismisses" the notification. It should launch APKGrabber and show the "Updates (x)" view.

**APKGrabber version:**
1.2.0

**Mobile phone and OS:**
OP5 with Android Pie (Oxygen OS 9.0.4).

**Error message text or screenshot:**
See attached iamges.

**Other info:**
This did not happen with APKGrabber 1.1.0 (or 1.0.0). Something to do with permissions? I haven't changed any such settings (to the best of my knowledge).

**Attached images:**
![APG_1](https://user-images.githubusercontent.com/7660277/56016381-af12ad80-5d04-11e9-9601-a396ae93dae3.jpg)
![APG_2](https://user-images.githubusercontent.com/7660277/56016383-afab4400-5d04-11e9-9c8a-d1a966bd41f8.jpg)

**Comment by tjsuominen** [comment] 2019-04-15 08:29
The same applies for APKGrabber itself - when 1.3.0 update notification came, clicking on the notification just closes the notification.

**Comment by tjsuominen** [comment] 2019-05-06 06:37
Hi @hemker - any news on this? Clicking on the notification does nothing (but makes the notification to disappear). Haven't updated yet to 1.4.0 (= issue with 1.3.0 on OP5).

**Comment by tjsuominen** [comment] 2019-05-10 06:43
Same applies for 1.4.0 = clicking on the notification does nothing but "removes" the notification i.e. does not open APKGrabber.

**Comment by TPS** [comment] 2019-05-10 11:10
@hemker Are you seeing these notes?  I wanted to check, as you've not replied @ all! 🙇🏾‍♂️

**Comment by hemker** [comment] 2019-05-10 11:21
I am receiving this all, but sorting/maintaining them is mainly limited to the weekend at the moment :(

Will take a look at it next.

Dennis

Am 10. Mai 2019 13:10:11 MESZ schrieb TPS <notifications@github.com>:

**Comment by hemker** [comment] 2019-05-10 20:14
@tjsuominen @TPS I think I identified the cause, working on a fix now. As soon as it's done, new release will be rolled out.

**Comment by hemker** [comment] 2019-05-10 21:02
@tjsuominen @TPS should be fixed now, please confirm.

**Comment by tjsuominen** [comment] 2019-05-18 08:43
@hemker Yes, clicking on the notification works now, thx!

**Closed** 2019-05-18 08:43 UTC
