### ISSUE TITLE
Crashes when (apparently) finding the same build on both APK Mirror & Google Play Store

### ISSUE THREAD

**Issue by Rool-IO** [hemker/apkgrabber#35] opened 2019-04-08 11:15 UTC
As the title says :

FATAL EXCEPTION: main
Process: de.apkgrabber, PID: 7728
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{baec2fa position=2 id=-1, oldPos=1, pLpos:1 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{80728af VFED..... ......I. 0,0-2560,1478 #7f1000b9 app:id/list_view}, adapter:de.apkgrabber.adapter.UpdaterAdapter@5b6f961, layout:android.support.v7.widget.LinearLayoutManager@312affb, context:de.apkgrabber.activity.MainActivity_@cc1947d
	at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5715)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5898)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3875)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3639)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1775)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:142)
	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:41)
	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1556)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:888)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1183)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:870)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:889)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

Only crashes when it'll (try to) combine both results in one entry.
(Restarting the app displays results as they should : app entry with apkmirror, install & ignore buttons)

**Comment by Rool-IO** [comment] 2019-05-10 21:41
Still happening with v1.4.2. Same crash log.

**Comment by hemker** [comment] 2019-05-11 16:23
Could be caused by a race condition. Will investigate that next.

**Comment by Rool-IO** [comment] 2019-08-31 06:26
Still happening, this time with Aptoide & APKMirror :
FATAL EXCEPTION: main
Process: de.apkgrabber, PID: 9940
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{c4d2e12 position=1 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] update tmpDetached no parent} android.support.v7.widget.RecyclerView{d791cd7 VFED..... ......I. 0,0-1312,2029 #7f1000b9 app:id/list_view}, adapter:de.apkgrabber.adapter.UpdaterAdapter@2b1d768, layout:android.support.v7.widget.LinearLayoutManager@2715c71, context:de.apkgrabber.activity.MainActivity_@aca73d6
	at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5715)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5898)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3875)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3639)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)
	at android.view.View.layout(View.java:21912)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
	at android.view.View.layout(View.java:21912)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:21912)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1775)
	at android.view.View.layout(View.java:21912)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:142)
	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:41)
	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1556)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:888)
	at android.view.View.layout(View.java:21912)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:21912)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:21912)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1183)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:870)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:889)
	at android.view.View.layout(View.java:21912)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:21912)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:21912)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:21912)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:21912)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
	at android.view.View.layout(View.java:21912)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3080)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2590)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
	at android.view.Choreographer.doFrame(Choreographer.java:725)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by Rool-IO** [comment] 2019-09-11 16:54
If of any help, today I had it again when APKGrabber found the same Play Store update on both APKMirror & Aptoide :
FATAL EXCEPTION: main
Process: de.apkgrabber, PID: 12133
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{ce0c11c position=2 id=-1, oldPos=1, pLpos:1 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{d31122f VFED..... ......ID 0,0-1312,2029 #7f1000b9 app:id/list_view}, adapter:de.apkgrabber.adapter.UpdaterAdapter@e1661ea, layout:android.support.v7.widget.LinearLayoutManager@29ed213, context:de.apkgrabber.activity.MainActivity_@85282c1
	at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5715)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5898)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3875)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3639)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1775)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:142)
	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:41)
	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1556)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:888)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1183)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:870)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:889)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3080)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2590)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
	at android.view.Choreographer.doFrame(Choreographer.java:725)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by Rool-IO** [comment] 2019-09-11 16:58
The app will only crash if staying in it.
If launching updates search & then going home, it won't crash but after finding the updates, tapping the notification will show an empty field whatever number of updates have been found.
Only workaround I found so far is to wait for a first entry to get displayed & immediately go home (or switch to another app) before it crashes.
(Auto search at app launch is disabled btw)

**Comment by Rool-IO** [comment] 2019-10-31 09:06
Still going on with current version (1.6.4) :

FATAL EXCEPTION: main
Process: de.apkgrabber, PID: 16841
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{9da5a13 position=1 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] update tmpDetached no parent} android.support.v7.widget.RecyclerView{5a525a6 VFED..... ......I. 0,0-1316,2029 #7f1000b9 app:id/list_view}, adapter:de.apkgrabber.adapter.UpdaterAdapter@acd9c13, layout:android.support.v7.widget.LinearLayoutManager@b4a08ae, context:de.apkgrabber.activity.MainActivity_@97243bd
	at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5715)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5898)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3875)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3639)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1775)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:142)
	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:41)
	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1556)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:888)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1183)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:870)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:889)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
	at android.view.View.layout(View.java:21927)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3080)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2590)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
	at android.view.Choreographer.doFrame(Choreographer.java:725)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by Rool-IO** [comment] 2020-01-09 11:33
Are you going to finally fix this crashing bug or not, sir ?

**Comment by hemker** [comment] 2020-01-09 19:21
Trying to fix that issue when I find some time for programming!

**Comment by Rool-IO** [comment] 2020-03-12 10:44
Haven't had any time yet to fix it ?

**Comment by TPS** [comment] 2020-03-12 16:39
@Rool-IO I'm sure a good PR would be accepted.  Are you volunteering?

**Comment by Rool-IO** [comment] 2020-03-18 13:11
@TPS I'm just a user, no point in me volunteering for a PR.
But other people with coding skills could.

**Comment by Rool-IO** [comment] 2020-04-21 13:48
More than a year with that crashing bug..
I truly hope a fix will be found and pushed sooner than later now..

**Comment by Rool-IO** [comment] 2020-08-26 08:45
@hemker Are you finally going to do something about it ?!

**Comment by hemker** [comment] 2020-08-26 09:05
I really would appreciate a PR, but I think no one will contribute to that bug solving. I have some spare time next week - the issue of merging two identical list view entries should be solvable. Could you please provide me a configuration on how to reproduce that crash?

**Comment by Rool-IO** [comment] 2020-09-30 19:03
@hemker Simply checking for Play Store updates on at least both APKmirror & Aptoide when newer builds are available on both should be enough to reproduce.

**Comment by hemker** [comment] 2020-10-29 10:10
@Rool-IO Could you please try using the latest stable (2.0.4) version of official APKUpdater? I consider contributing there instead of fixing stuff that might already be fixed.

**Comment by Rool-IO** [comment] 2020-10-31 12:49
@hemker Well I can't : APKUpdater 2.0.4 isn't working properly anymore for me and it's been a while.
As a matter of fact, this APKGrabber bug still is happening so I hope you'd rather fix yours.

**Comment by Rool-IO** [comment] 2020-11-18 11:18
@hemker ? Any progress ? I guess not...

**Comment by hemker** [comment] 2020-11-19 20:47
@Rool-IO found the error! I'm thinking how to fix it best, new release should be out next days!

**Comment by Rool-IO** [comment] 2020-11-20 11:47
@hemker Wonderful ! Looking forward to it

**Comment by hemker** [comment] 2020-11-20 15:18
@Rool-IO release is out, please confirm if bug is fixed!

**Comment by Rool-IO** [comment] 2020-11-20 17:15
@hemker Thanks. Installed. Will do as soon as new builds are available for selected apps on all stores (Play, APK mirror & Aptoide).

**Comment by Rool-IO** [comment] 2020-11-27 15:50
@hemker Bug seems to be fixed indeed.
Tested with both 1.6.5 & 1.6.6 builds.

**Comment by hemker** [comment] 2020-11-29 16:09
@Rool-IO thanks, closing this now, finally :D

**Closed by hemker** 2020-11-29 16:09 UTC
